import React, { useState, useEffect } from 'react';
import { Sparkles, RefreshCw, CheckCircle2, FileText, Activity, AlertCircle, Loader2 } from 'lucide-react';
import { api } from '../../../services/api';

export const AISummaryTab = ({ patient, onReloadPatient }) => {
  const [summary, setSummary] = useState(patient?.aiSummary || null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchOrGenerateSummary = async (force = false) => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.getAiSummary(patient.id, force);
      if (res.success) {
        setSummary(res.aiSummary);
        if (onReloadPatient) onReloadPatient();
      }
    } catch (err) {
      setError(err.message || 'Failed to generate AI Patient Summary');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!summary && patient) {
      fetchOrGenerateSummary(false);
    }
  }, [patient]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-gray-200 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-sky-700" />
            <h3 className="text-base font-bold text-black">AI Patient Synthesis & Clinical Summary</h3>
          </div>
          <p className="text-xs text-gray-600">Automated medical overview generated by Google Gemini API combining all available records.</p>
        </div>

        <button
          onClick={() => fetchOrGenerateSummary(true)}
          disabled={loading}
          className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-black bg-sky-100 border border-sky-300 rounded hover:bg-sky-200 transition-colors disabled:opacity-50"
        >
          {loading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" />}
          <span>Re-Generate Summary</span>
        </button>
      </div>

      {error && (
        <div className="p-3 bg-red-50 border border-red-200 text-red-700 text-xs rounded-md font-medium">
          {error}
        </div>
      )}

      {loading ? (
        <div className="p-12 text-center bg-white border border-gray-200 rounded-lg space-y-3">
          <Loader2 className="w-8 h-8 text-black animate-spin mx-auto" />
          <p className="text-sm font-semibold text-black">Synthesizing Patient Records with Google Gemini AI...</p>
          <p className="text-xs text-gray-500">Reading lab reports, doctor notes, prescriptions & medical history.</p>
        </div>
      ) : summary ? (
        <div className="bg-white border border-gray-200 rounded-lg p-6 space-y-6 shadow-2xs">
          {/* Top Patient Header Card */}
          <div className="bg-sky-50 border border-sky-200 rounded-md p-4 flex flex-wrap items-center justify-between gap-4">
            <div>
              <span className="text-[10px] font-bold text-gray-600 uppercase tracking-wider font-mono">Patient Subject</span>
              <h4 className="text-lg font-bold text-black">{summary.patientName || patient.name}</h4>
              <p className="text-xs text-gray-700 font-mono">Age: {summary.age || patient.age} • Last Visit: {summary.lastVisit || patient.last_visit}</p>
            </div>

            <div className="bg-white px-3 py-2 rounded border border-sky-200 text-right">
              <span className="text-[10px] font-bold text-gray-600 uppercase font-mono block">Known Condition</span>
              <span className="text-xs font-bold text-black">{summary.knownCondition || patient.disease}</span>
            </div>
          </div>

          {/* Structured Sections */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 bg-gray-50 rounded-md border border-gray-200 space-y-1">
              <h5 className="text-xs font-bold text-black uppercase tracking-wider flex items-center gap-1.5 mb-2">
                <Activity className="w-4 h-4 text-sky-800" />
                1. Important Medical History
              </h5>
              <p className="text-xs text-gray-800 leading-relaxed font-medium">
                {summary.importantMedicalHistory}
              </p>
            </div>

            <div className="p-4 bg-gray-50 rounded-md border border-gray-200 space-y-1">
              <h5 className="text-xs font-bold text-black uppercase tracking-wider flex items-center gap-1.5 mb-2">
                <FileText className="w-4 h-4 text-sky-800" />
                2. Recent Reports & Diagnostics
              </h5>
              <p className="text-xs text-gray-800 leading-relaxed font-medium">
                {summary.recentReports}
              </p>
            </div>

            <div className="p-4 bg-gray-50 rounded-md border border-gray-200 space-y-1">
              <h5 className="text-xs font-bold text-black uppercase tracking-wider flex items-center gap-1.5 mb-2">
                <CheckCircle2 className="w-4 h-4 text-sky-800" />
                3. Current Prescriptions & Medications
              </h5>
              <p className="text-xs text-gray-800 leading-relaxed font-medium font-mono">
                {summary.currentPrescriptions}
              </p>
            </div>

            <div className="p-4 bg-sky-50/80 rounded-md border border-sky-300 space-y-1">
              <h5 className="text-xs font-bold text-black uppercase tracking-wider flex items-center gap-1.5 mb-2">
                <Sparkles className="w-4 h-4 text-sky-900" />
                4. Important Clinical Observations
              </h5>
              <p className="text-xs text-black leading-relaxed font-semibold">
                {summary.importantObservations}
              </p>
            </div>
          </div>

          {/* AI Notice */}
          <div className="pt-2 border-t border-gray-100 flex items-center justify-between text-[11px] text-gray-500">
            <span>Generated on {new Date(summary.generatedAt || Date.now()).toLocaleString()} via Google Gemini API</span>
            <span className="italic">* Always verify AI summary with attending physician</span>
          </div>
        </div>
      ) : (
        <div className="p-8 text-center bg-gray-50 border border-gray-200 rounded-lg">
          <Sparkles className="w-8 h-8 text-gray-400 mx-auto mb-2" />
          <p className="text-sm font-semibold text-black">No Summary Available</p>
          <button
            onClick={() => fetchOrGenerateSummary(true)}
            className="mt-3 px-4 py-2 text-xs font-bold text-white bg-black rounded hover:bg-gray-800 transition-colors"
          >
            Generate AI Summary
          </button>
        </div>
      )}
    </div>
  );
};
